server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/optimization_test_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  threads:
    virtual:
      enabled: false